var json_comedoresactivos_1 = {
"type": "FeatureCollection",
"name": "comedoresactivos_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Nombre": "COMEDOR DE LA FAMILIA", "cant_dias": "2", "niños": "120", "adultos": "0", "Almacenaje": "SUFICIENTE", "Luz": "NO", "Gas": "NO", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "6", "Nro_volunt": "6", "Apoyo_esco": "NO", "DESAYUNO": "NO", "MERIENDA": "SI", "ALMUERZO": "SI", "CENA": null, "Estado": "ACTIVO", "Personas": "120" }, "geometry": { "type": "Point", "coordinates": [ -58.732062400045663, -38.54703543331852 ] } },
{ "type": "Feature", "properties": { "Nombre": "PEQUEÑOS GIGANTES", "cant_dias": "6", "niños": "50", "adultos": "30", "Almacenaje": "INSUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "7", "Nro_volunt": "7", "Apoyo_esco": "TRAMT", "DESAYUNO": "SI", "MERIENDA": "SI", "ALMUERZO": "NO", "CENA": null, "Estado": "ACTIVO", "Personas": "80" }, "geometry": { "type": "Point", "coordinates": [ -58.761365890725493, -38.543309577072485 ] } },
{ "type": "Feature", "properties": { "Nombre": "CENTRO COMUNITARIO MATEO", "cant_dias": "6", "niños": null, "adultos": null, "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "11", "Nro_volunt": "11", "Apoyo_esco": null, "DESAYUNO": "NO", "MERIENDA": "NO", "ALMUERZO": "NO", "CENA": null, "Estado": "ACTIVO", "Personas": "0" }, "geometry": { "type": "Point", "coordinates": [ -58.752411068786884, -38.546690484807364 ] } },
{ "type": "Feature", "properties": { "Nombre": "COMEDOR GENERAL SAN MARTIN", "cant_dias": "5", "niños": "92", "adultos": "92", "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "3", "Nro_volunt": "0", "Apoyo_esco": "NO", "DESAYUNO": "SI", "MERIENDA": "NO", "ALMUERZO": "NO", "CENA": null, "Estado": "ACTIVO", "Personas": "184" }, "geometry": { "type": "Point", "coordinates": [ -58.758732680003575, -38.560859952453612 ] } },
{ "type": "Feature", "properties": { "Nombre": "COMEDOR SUR", "cant_dias": "5", "niños": "40", "adultos": "21", "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "2", "Nro_volunt": "0", "Apoyo_esco": "NO", "DESAYUNO": "NO", "MERIENDA": "SI", "ALMUERZO": "NO", "CENA": null, "Estado": "ACTIVO", "Personas": "61" }, "geometry": { "type": "Point", "coordinates": [ -58.74055646966724, -38.567038145318655 ] } },
{ "type": "Feature", "properties": { "Nombre": "PRECIOSA SEMILLA", "cant_dias": "7", "niños": "12", "adultos": "0", "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "12", "Nro_volunt": "0", "Apoyo_esco": "SI", "DESAYUNO": "SI", "MERIENDA": "SI", "ALMUERZO": "SI", "CENA": null, "Estado": "ACTIVO", "Personas": "12" }, "geometry": { "type": "Point", "coordinates": [ -58.738913574567341, -38.557550833995592 ] } },
{ "type": "Feature", "properties": { "Nombre": "LA CASITA PARA MERENDAR", "cant_dias": "5", "niños": "35", "adultos": "0", "Almacenaje": "INSUFICIENTE", "Luz": "SI", "Gas": "NO", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "3", "Nro_volunt": "0", "Apoyo_esco": "SI", "DESAYUNO": "SI", "MERIENDA": "NO", "ALMUERZO": "SI", "CENA": null, "Estado": "ACTIVO", "Personas": "35" }, "geometry": { "type": "Point", "coordinates": [ -58.759889272274123, -38.555137192372321 ] } },
{ "type": "Feature", "properties": { "Nombre": "LOS MALVONES", "cant_dias": "7", "niños": "32", "adultos": "0", "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "POCO", "Nro_trabaj": "10", "Nro_volunt": "10", "Apoyo_esco": "SI", "DESAYUNO": "SI", "MERIENDA": "SI", "ALMUERZO": "SI", "CENA": null, "Estado": "ACTIVO", "Personas": "32" }, "geometry": { "type": "Point", "coordinates": [ -58.769261123808931, -38.539060925021687 ] } },
{ "type": "Feature", "properties": { "Nombre": "HOGAR EMANUEL", "cant_dias": "7", "niños": "3", "adultos": "6", "Almacenaje": "INSUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "1", "Nro_volunt": "1", "Apoyo_esco": "NO", "DESAYUNO": "SI", "MERIENDA": "SI", "ALMUERZO": "SI", "CENA": null, "Estado": "ACTIVO", "Personas": "9" }, "geometry": { "type": "Point", "coordinates": [ -58.734017678255888, -38.566393623154866 ] } },
{ "type": "Feature", "properties": { "Nombre": "SOLIDARIDAD EN MARCHA", "cant_dias": "5", "niños": "65", "adultos": "0", "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "25", "Nro_volunt": "12", "Apoyo_esco": "SI", "DESAYUNO": "SI", "MERIENDA": "NO", "ALMUERZO": "NO", "CENA": null, "Estado": "ACTIVO", "Personas": "65" }, "geometry": { "type": "Point", "coordinates": [ -58.75328890669109, -38.538298589879652 ] } },
{ "type": "Feature", "properties": { "Nombre": "UNA SONRISA DE BARRIOS DE PIE", "cant_dias": "3", "niños": null, "adultos": null, "Almacenaje": "INSUFICIENTE", "Luz": "NO", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "38", "Nro_volunt": null, "Apoyo_esco": "SI", "DESAYUNO": "SI", "MERIENDA": "NO", "ALMUERZO": "SI", "CENA": null, "Estado": "ACTIVO", "Personas": "0" }, "geometry": { "type": "Point", "coordinates": [ -58.717700876849015, -38.554373577630379 ] } },
{ "type": "Feature", "properties": { "Nombre": "PUENTE COLGANTE", "cant_dias": "7", "niños": "106", "adultos": "70", "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "SI", "Nro_trabaj": "3", "Nro_volunt": "3", "Apoyo_esco": "NO", "DESAYUNO": "NO", "MERIENDA": "NO", "ALMUERZO": "SI", "CENA": "NO", "Estado": "ACTIVO", "Personas": "176" }, "geometry": { "type": "Point", "coordinates": [ -58.724509876730878, -38.549232474982766 ] } },
{ "type": "Feature", "properties": { "Nombre": "ALFA Y OMEGA", "cant_dias": "1", "niños": "15", "adultos": "0", "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "6", "Nro_volunt": "6", "Apoyo_esco": "NO", "DESAYUNO": "NO", "MERIENDA": "NO", "ALMUERZO": "SI", "CENA": "NO", "Estado": "ACTIVO", "Personas": "15" }, "geometry": { "type": "Point", "coordinates": [ -58.708196250036423, -38.559096757444706 ] } },
{ "type": "Feature", "properties": { "Nombre": "EL PAPI", "cant_dias": "1", "niños": "20", "adultos": "15", "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "NO", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "2", "Nro_volunt": "2", "Apoyo_esco": "NO", "DESAYUNO": "NO", "MERIENDA": "NO", "ALMUERZO": "SI", "CENA": "NO", "Estado": "ACTIVO", "Personas": "35" }, "geometry": { "type": "Point", "coordinates": [ -58.73784214244538, -38.539520031322233 ] } },
{ "type": "Feature", "properties": { "Nombre": "CARITAS STA. MAGDALENA CANOSSA", "cant_dias": "3", "niños": "20", "adultos": null, "Almacenaje": "SUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "MUCHO", "Nro_trabaj": "15", "Nro_volunt": "15", "Apoyo_esco": "SI", "DESAYUNO": "NO", "MERIENDA": "SI", "ALMUERZO": "SI", "CENA": "NO", "Estado": "ACTIVO", "Personas": "20" }, "geometry": { "type": "Point", "coordinates": [ -58.716826039882406, -38.545219679549682 ] } },
{ "type": "Feature", "properties": { "Nombre": "MATE COCIDO", "cant_dias": "5", "niños": "100", "adultos": "0", "Almacenaje": "INSUFICIENTE", "Luz": "SI", "Gas": "SI", "Agua": "SI", "Mantenimie": "POCO", "Nro_trabaj": "3", "Nro_volunt": "8", "Apoyo_esco": "SI", "DESAYUNO": "NO", "MERIENDA": "NO", "ALMUERZO": "SI", "CENA": "NO", "Estado": "ACTIVO", "Personas": "100" }, "geometry": { "type": "Point", "coordinates": [ -58.735898406328033, -38.541118710172547 ] } }
]
}
